[meta]
name        = "s314ke Medals"
author      = "Mattynator"
category    = "MattyPlugins"
version     = "0.4.4"

[script]
dependencies = [ "NadeoServices" ]
optional_dependencies = [ "UltimateMedalsExtended" ]
exports = [ "exports/export.as" ]